# Server 설정
server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
# 로깅 설정
# TRACE -> DEBUG -> INFO -> WARN -> ERROR
logging:
  level:
    root: INFO
spring:
  ai:
    openai:
      api-key: ${AI_API_KEY}
      embedding:
        options:
          model: text-embedding-ada-002
  data:
    mongodb:
      host: ${DB_HOST}
      port: 27017
      username: ${DB_USER}
      password: ${DB_PWD}
      database: fastfood

